# Generated by Django 5.0 on 2024-07-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semana',
            name='semana',
            field=models.IntegerField(db_index=True),
        ),
    ]
