# Generated by Django 5.0 on 2024-07-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("C1", "0003_detalle_menu_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumno",
            name="password",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="tipo_menu",
            name="cantidad",
            field=models.IntegerField(null=True),
        ),
    ]
